stages:
  - test
  - build_lib
  - build_integration
  - docs

build_library:
  stage: build_lib
  tags:
    - shell
  script:
    - source setup_env
    - rm -rf build/
    - mkdir build
    - cd build
    - cmake -DLT_CRYPTO=trezor_crypto ..
    - make

build_integration_tests:
  stage: build_integration
  tags:
    - shell
  script:
    - source setup_env
    - cd tests/integration/
    - mkdir build
    - cd build
    - cmake -DLT_CRYPTO=trezor_crypto ..
    - make

LT_BUILD_DOCS:
  stage: docs
  tags:
    - shell
  script:
    - source setup_env
    - rm -rf build/
    - mkdir build
    - cd build
    - cmake -DLT_BUILD_DOCS=1 ..
    - make doc_doxygen
    - cd docs/doxygen/latex
    - make
    - mv refman.pdf libtropic.pdf
    - mv libtropic.pdf ../../../../
  artifacts:
    paths:
      - libtropic.pdf
