site_name: Libtropic SDK Documentation
site_url: https://medexs.github.io/libtropic-fork/
repo_url: https://github.com/tropicsquare/libtropic
repo_name: tropicsquare/libtropic
site_description: SDK for an application development with TROPIC01 secure element.
site_author: Tropic Square
site_dir: docs_build/

# Theme configuration
theme:
  name: material
  font:
    text: Inter
  icon:
    repo: fontawesome/brands/github
  logo: img/TS_logo_white_symbol.svg
  favicon: img/tropic_symbol.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      # accent: pink
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      # accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      # accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.suggest

# Navigation menu setup
nav:
  - Introduction: index.md
  - API Reference:
    - doxygen/build/html/index.html
  - Examples:
    - examples/index.md
    - Reversible Examples: examples/reversible_examples.md
    - Irreversible Examples: examples/irreversible_examples.md
  - Tests:
    - tests/index.md
    - Functional Tests: tests/functional_tests.md
    - Unit Tests: tests/unit_tests.md
  - For Developers:
    - for_developers/index.md
    - Libtropic Architecture: for_developers/libtropic_architecture.md
    - Adding New Embedded Platform: for_developers/adding_embedded_platform.md
    - Adding New Cryptographic Backend: for_developers/adding_crypto_backend.md
    - Compile libtropic as Static Archive: for_developers/compile_as_static_archive.md
    - Debugging: for_developers/debugging.md
    - Logging: for_developers/logging.md
    - Randomization: for_developers/randomization.md
    - Run Static Analysis: for_developers/static_analysis.md
    - Code Formatter: for_developers/code_formatter.md
  - Other:
    - other/index.md
    - TROPIC01 Model: other/tropic01_model.md
    - Provisioning Data: other/provisioning_data.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - github-callouts  # Allows GitHub alerts in Markdown
  # Following extensions can be used for wider Markdown syntax support
  - admonition
  - pymdownx.arithmatex    # For math rendering (optional)
  - pymdownx.betterem      # Better emphasis handling
  - pymdownx.caret         # Superscripts
  - pymdownx.critic        # Suggestions / strike-through
  - pymdownx.details       # Collapsible sections
  - pymdownx.highlight     # Extra code highlighting
  - pymdownx.inlinehilite  # Inline code highlighting
  - pymdownx.superfences   # Fenced code blocks
  - pymdownx.tasklist      # Checklists

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/tropicsquare
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/tropic-square-s-r-o
    - icon: fontawesome/brands/github
      link: https://github.com/tropicsquare/libtropic

extra_css:
  - stylesheets/extra.css