syntax = "proto3";

// ============================== UsbDevkitCmd ===============================
message UsbDevkitCmd {
	oneof type {
		AppCmd app = 1;
		RawCmd raw = 2;
	}
}
// ===========================================================================



// ============================== UsbDevkitResp ==============================
message UsbDevkitResp {
	oneof type {
		AppResp app = 1;
		RawResp raw = 2;
		ErrorResp error = 3;
	}
}
// ===========================================================================



// ================================= AppCmd ==================================
message AppCmd {
	oneof type {
		PinSetCmd pin_set = 1;
		PinVerifyCmd pin_verify = 2;
		RMemReadCmd r_mem_read = 3;
		RMemWriteCmd r_mem_write = 4;
	}
}
// ------------------------------- PinSetCmd
message PinSetCmd {
	string new_pin = 1;
	uint32 attempts = 2;
	optional bytes additional_data = 3;
	bytes secret = 4;
}
// ------------------------------- PinVerifyCmd
message PinVerifyCmd {
	string pin = 1;
	optional bytes additional_data = 2;
}
// ------------------------------- RMemReadCmd
message RMemReadCmd {
	uint32 udata_slot = 1;
}
// ------------------------------- RMemWriteCmd
message RMemWriteCmd {
	uint32 udata_slot = 1;
	bytes data = 2;
}
// ===========================================================================



// ================================= AppResp =================================
message AppResp {
	oneof type {
		PinSetResp pin_set = 1;
		PinVerifyResp pin_verify = 2;
		RMemReadResp r_mem_read = 3;
		RMemWriteResp r_mem_write = 4;
	}
	optional uint32 libtropic_error_code = 5;
}
// ------------------------------- PinSetResp
message PinSetResp {
	PinSetRespCode res_code = 1;
	bytes crypto_key = 2;
}
enum PinSetRespCode {
	PIN_SET_RESP_CODE_UNSPECIFIED = 0;
	PIN_SET_RESP_CODE_OK = 1;
	PIN_SET_RESP_CODE_ERROR = 2;
	PIN_SET_RESP_CODE_ATTEMPS_OUT_OF_RANGE = 3;
	PIN_SET_RESP_CODE_FLASH_WRITE_ERROR = 4;
}
// ------------------------------- PinVerifyResp
message PinVerifyResp {
	PinVerifyRespCode res_code = 1;
	bytes crypto_key = 3;
}
enum PinVerifyRespCode {
	PIN_VERIFY_RESP_CODE_UNSPECIFIED = 0;
	PIN_VERIFY_RESP_CODE_OK = 1;
	PIN_VERIFY_RESP_CODE_ERROR = 2;
	PIN_VERIFY_RESP_CODE_DEPLETED_ATTEMPS_OUT_OF_RANGE = 3;
	PIN_VERIFY_RESP_CODE_WRONG_PIN = 4;
	PIN_VERIFY_RESP_CODE_FLASH_READ_ERROR = 5;
	PIN_VERIFY_RESP_CODE_FLASH_WRITE_ERROR = 6;
}
// ------------------------------- RMemReadResp
message RMemReadResp {
	RMemReadRespCode res_code = 1;
	bytes data = 2;
}
enum RMemReadRespCode {
	R_MEM_READ_RESP_CODE_UNSPECIFIED = 0;
	R_MEM_READ_RESP_CODE_OK = 1;
	R_MEM_READ_RESP_CODE_ERROR = 2;
}
// ------------------------------- RMemWriteResp
message RMemWriteResp {
	RMemWriteRespCode res_code = 1;
}
enum RMemWriteRespCode {
	R_MEM_WRITE_RESP_CODE_UNSPECIFIED = 0;
	R_MEM_WRITE_RESP_CODE_OK = 1;
	R_MEM_WRITE_RESP_CODE_ERROR = 2;
}
// ===========================================================================



// ================================= RawCmd ==================================
message RawCmd {
	oneof type {
		SendSpiDataCmd send_spi_data = 1;
		SetAutoCsModeCmd set_auto_cs_mode = 2;
		SetCsCmd set_cs = 3;
		SetTr01PwrCmd set_tr01_pwr = 4;
		GetGpoCmd get_gpo = 5;
	}
}
// ------------------------------- SendSpiDataCmd
message SendSpiDataCmd {
	bytes tx_data = 1;
	uint32 timeout_ms = 2;
}
// ------------------------------- SetAutoCsModeCmd
message SetAutoCsModeCmd {
	bool on = 1;
}
// ------------------------------- SetCsCmd
message SetCsCmd {
	bool high = 1;
}
// ------------------------------- SetTr01PwrCmd
message SetTr01PwrCmd {
	bool on = 1;
}
// ------------------------------- GetGpoCmd
message GetGpoCmd {
	// Empty command used to read TROPIC01 GPO pin.
}
// ===========================================================================



// ================================= RawResp =================================
message RawResp {
	oneof type {
		SendSpiDataResp send_spi_data = 1;
		SetAutoCsModeResp set_auto_cs_mode = 2;
		SetCsResp set_cs = 3;
		SetTr01PwrResp set_tr01_pwr = 4;
		GetGpoResp get_gpo = 5;
	}
}
// ------------------------------- SendSpiDataResp
message SendSpiDataResp {
	SendSpiDataRespCode res_code = 1;
	bytes rx_data = 2;
}
enum SendSpiDataRespCode {
	SEND_SPI_DATA_RESP_CODE_UNSPECIFIED = 0;
	SEND_SPI_DATA_RESP_CODE_OK = 1;
	SEND_SPI_DATA_RESP_CODE_ERROR = 2;
	SEND_SPI_DATA_RESP_CODE_BUSY = 3;
	SEND_SPI_DATA_RESP_CODE_TIMEOUT = 4;
}
// ------------------------------- SetAutoCsModeResp
message SetAutoCsModeResp {
	SetAutoCsModeRespCode res_code = 1;
}
enum SetAutoCsModeRespCode {
	SET_AUTO_CS_MODE_RESP_CODE_UNSPECIFIED = 0;
	SET_AUTO_CS_MODE_RESP_CODE_OK = 1;
}
// ------------------------------- SetCsResp
message SetCsResp {
	SetCsRespCode res_code = 1;
}
enum SetCsRespCode {
	SET_CS_RESP_CODE_UNSPECIFIED = 0;
	SET_CS_RESP_CODE_OK = 1;
	SET_CS_RESP_CODE_AUTO_CS_MODE_ON = 2;
}
// ------------------------------- SetTr01PwrResp
message SetTr01PwrResp {
	SetTr01PwrRespCode res_code = 1;
}
enum SetTr01PwrRespCode {
	SET_TR01_PWR_RESP_CODE_UNSPECIFIED = 0;
	SET_TR01_PWR_RESP_CODE_OK = 1;
}
// ------------------------------- GetGpoResp
message GetGpoResp {
	GetGpoRespCode res_code = 1;
	bool high = 2;
}
enum GetGpoRespCode {
	GET_GPO_RESP_CODE_UNSPECIFIED = 0;
	GET_GPO_RESP_CODE_OK = 1;
}
// ===========================================================================



// ================================ ErrorResp ================================
message ErrorResp {
	ErrorRespCode res_code = 1;
}
enum ErrorRespCode {
	ERROR_RESP_CODE_UNSPECIFIED = 0;
	ERROR_RESP_CODE_BAD_DATA_LEN = 1;
	ERROR_RESP_CODE_BAD_CRC = 2;
	ERROR_RESP_CODE_PB_DECODE = 3;
	ERROR_RESP_CODE_UNKNOWN_CMD = 4;
}
// ===========================================================================