/**
 * @file lt_ex_fw_update.c
 * @name Firmware update
 * @brief This code performs firmware update of TROPIC01 chip. Use defines at the beginning of this file to specify
 * firmware version and slot.
 *
 * @note We recommend reading TROPIC01's datasheet before diving into this example!
 *
 * @author Tropic Square s.r.o.
 *
 * @license For the license see file LICENSE.txt file in the root directory of this source tree.
 */

#include <inttypes.h>

#include "libtropic.h"
#include "libtropic_common.h"
#include "libtropic_examples.h"
#include "libtropic_logging.h"
#include "string.h"
// Include here a particular firmware from TROPIC01_fw_update_files (in a form of header file)
#include "fw_CPU_0_3_1.h"

/** @brief Name of a variable in a particular firmware header file
 that contains the firmware binary data.
 This is a variable defined in the header file generated by the build system into a
 'TROPIC01_fw_update_files' directory. */
#define FW_UPDATE_DATA fw_CPU_0_3_1
/** @brief Firmware bank */
#define FW_UPDATE_BANK FW_BANK_FW2

/** @brief Size of the print buffer. */
#define PRINT_BUFF_SIZE 196

static void print_headers(lt_handle_t *h)
{
    lt_ret_t ret;
    char print_buff[PRINT_BUFF_SIZE];
    LT_LOG("  Chip contains following headers:");
    uint8_t header[LT_L2_GET_INFO_FW_HEADER_SIZE] = {0};
    LT_LOG("    lt_get_info_fw_bank()  FW_BANK_FW1        %s",
           lt_ret_verbose(lt_get_info_fw_bank(h, FW_BANK_FW1, header, LT_L2_GET_INFO_FW_HEADER_SIZE)));

    ret = lt_print_bytes(header, 10, print_buff, PRINT_BUFF_SIZE);
    if (LT_OK != ret) LT_LOG_ERROR("lt_print_bytes failed, ret=%s", lt_ret_verbose(ret));
    LT_LOG("    Header:                                   %s", print_buff);

    ret = lt_print_bytes(header + 10, 10, print_buff, PRINT_BUFF_SIZE);
    if (LT_OK != ret) LT_LOG_ERROR("lt_print_bytes failed, ret=%s", lt_ret_verbose(ret));
    LT_LOG("                                              %s", print_buff);

    LT_LOG("    lt_get_info_fw_bank()  FW_BANK_FW2        %s",
           lt_ret_verbose(lt_get_info_fw_bank(h, FW_BANK_FW2, header, LT_L2_GET_INFO_FW_HEADER_SIZE)));

    ret = lt_print_bytes(header, 10, print_buff, PRINT_BUFF_SIZE);
    if (LT_OK != ret) LT_LOG_ERROR("lt_print_bytes failed, ret=%s", lt_ret_verbose(ret));
    LT_LOG("    Header:                                   %s", print_buff);

    ret = lt_print_bytes(header + 10, 10, print_buff, PRINT_BUFF_SIZE);
    if (LT_OK != ret) LT_LOG_ERROR("lt_print_bytes failed, ret=%s", lt_ret_verbose(ret));
    LT_LOG("                                              %s", print_buff);

    LT_LOG("    lt_get_info_fw_bank()  FW_BANK_SPECT1     %s",
           lt_ret_verbose(lt_get_info_fw_bank(h, FW_BANK_SPECT1, header, LT_L2_GET_INFO_FW_HEADER_SIZE)));

    ret = lt_print_bytes(header, 10, print_buff, PRINT_BUFF_SIZE);
    if (LT_OK != ret) LT_LOG_ERROR("lt_print_bytes failed, ret=%s", lt_ret_verbose(ret));
    LT_LOG("    Header:                                   %s", print_buff);

    ret = lt_print_bytes(header + 10, 10, print_buff, PRINT_BUFF_SIZE);
    if (LT_OK != ret) LT_LOG_ERROR("lt_print_bytes failed, ret=%s", lt_ret_verbose(ret));
    LT_LOG("                                              %s", print_buff);

    LT_LOG("    lt_get_info_fw_bank()  FW_BANK_SPECT2     %s",
           lt_ret_verbose(lt_get_info_fw_bank(h, FW_BANK_SPECT2, header, LT_L2_GET_INFO_FW_HEADER_SIZE)));

    ret = lt_print_bytes(header, 10, print_buff, PRINT_BUFF_SIZE);
    if (LT_OK != ret) LT_LOG_ERROR("lt_print_bytes failed, ret=%s", lt_ret_verbose(ret));
    LT_LOG("    Header:                                   %s", print_buff);

    ret = lt_print_bytes(header + 10, 10, print_buff, PRINT_BUFF_SIZE);
    if (LT_OK != ret) LT_LOG_ERROR("lt_print_bytes failed, ret=%s", lt_ret_verbose(ret));
    LT_LOG("                                              %s", print_buff);
}

int lt_ex_fw_update(lt_handle_t *h)
{
    LT_LOG("\t=======================================================================");
    LT_LOG("\t=====  TROPIC01 FW update                                           ===");
    LT_LOG("\t=======================================================================");

    lt_ret_t ret = LT_FAIL;

    lt_init(h);

    // Reused variable
    uint8_t fw_ver[LT_L2_GET_INFO_RISCV_FW_SIZE] = {0};

    // First check in which mode chip operates, bootloader or application
    LT_LOG("lt_update_mode()                              %s", lt_ret_verbose(lt_update_mode(h)));
    if (h->l2.mode == LT_MODE_APP) {
        LT_LOG("  Chip is executing application firmware");
        // App runs so we can see what firmwares are running
        // RISCV app firmware version
        ret = lt_get_info_riscv_fw_ver(h, fw_ver, LT_L2_GET_INFO_RISCV_FW_SIZE);
        if (ret != LT_OK) {
            LT_LOG("     lt_get_info_riscv_fw_ver()               %s", lt_ret_verbose(ret));
        }
        else {
            LT_LOG("lt_get_info_riscv_fw_ver()                    %s", lt_ret_verbose(ret));
            LT_LOG("  riscv_fw_ver: %d.%d.%d    (+ unused %d)", fw_ver[3], fw_ver[2], fw_ver[1], fw_ver[0]);
        }

        // SPECT firmware version
        ret = lt_get_info_spect_fw_ver(h, fw_ver, LT_L2_GET_INFO_SPECT_FW_SIZE);
        if (ret != LT_OK) {
            LT_LOG("     lt_get_info_spect_fw_ver()               %s", lt_ret_verbose(ret));
        }
        else {
            LT_LOG("lt_get_info_spect_fw_ver()                    %s", lt_ret_verbose(ret));
            LT_LOG("  spect_fw_ver: %d.%d.%d    (+ unused %d)", fw_ver[3], fw_ver[2], fw_ver[1], fw_ver[0]);
        }
        // Now reboot into STARTUP (bootloader)
        LT_LOG("lt_reboot() reboot into STARTUP               %s", lt_ret_verbose(lt_reboot(h, LT_MODE_MAINTENANCE)));
    }

    // Check again mode
    LT_LOG_LINE();
    LT_LOG("lt_update_mode()                              %s", lt_ret_verbose(lt_update_mode(h)));
    if (h->l2.mode == LT_MODE_MAINTENANCE) {
        LT_LOG("  Chip is executing bootloader");
        // Chip must be in startup mode now.
        // Get bootloader version by issuing "Read riscv fw version" request while chip is in maintenance:
        LT_LOG("  lt_get_info_riscv_fw_ver()                  %s",
               lt_ret_verbose(lt_get_info_riscv_fw_ver(h, fw_ver, LT_L2_GET_INFO_RISCV_FW_SIZE)));
        LT_LOG("  Bootloader version: %d.%d.%d    (+ unused %d)", fw_ver[3] & 0x7f, fw_ver[2], fw_ver[1], fw_ver[0]);

        print_headers(h);

        if (1) {
            // Erase firmware bank
            LT_LOG("lt_mutable_fw_erase()                    %s",
                   lt_ret_verbose(lt_mutable_fw_erase(h, FW_UPDATE_BANK)));
            // Update firmware bank
            LT_LOG("lt_mutable_fw_update()                   %s",
                   lt_ret_verbose(lt_mutable_fw_update(h, FW_UPDATE_DATA, sizeof(fw_CPU_0_3_1), FW_UPDATE_BANK)));

            print_headers(h);
        }
        else {
            LT_LOG("Update disabled");
        }
    }
    else {
        LT_LOG("     ERROR device couldn't get into STARTUP mode");
        return -1;
    }
    LT_LOG_LINE();
    LT_LOG("lt_reboot() reboot                            %s", lt_ret_verbose(lt_reboot(h, LT_MODE_APP)));
    LT_LOG("lt_get_info_riscv_fw_ver()                    %s",
           lt_ret_verbose(lt_get_info_riscv_fw_ver(h, fw_ver, LT_L2_GET_INFO_RISCV_FW_SIZE)));
    LT_LOG("riscv_fw_ver: %d.%d.%d    (+ unused %d)", fw_ver[3], fw_ver[2], fw_ver[1], fw_ver[0]);
    LT_LOG("lt_get_info_spect_fw_ver()                    %s",
           lt_ret_verbose(lt_get_info_spect_fw_ver(h, fw_ver, LT_L2_GET_INFO_SPECT_FW_SIZE)));
    LT_LOG("spect_fw_ver: %d.%d.%d    (+ unused %d)", fw_ver[3], fw_ver[2], fw_ver[1], fw_ver[0]);

    return 0;
}
