/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_USB_DEVKIT_MESSAGES_PB_H_INCLUDED
#define PB_USB_DEVKIT_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _PinSetRespCode {
    PIN_SET_RESP_CODE_UNSPECIFIED = 0,
    PIN_SET_RESP_CODE_OK = 1,
    PIN_SET_RESP_CODE_ERROR = 2,
    PIN_SET_RESP_CODE_ATTEMPS_OUT_OF_RANGE = 3,
    PIN_SET_RESP_CODE_FLASH_WRITE_ERROR = 4,
    PIN_SET_RESP_CODE_KDF_ERROR = 5
} PinSetRespCode;

typedef enum _PinVerifyRespCode {
    PIN_VERIFY_RESP_CODE_UNSPECIFIED = 0,
    PIN_VERIFY_RESP_CODE_OK = 1,
    PIN_VERIFY_RESP_CODE_ERROR = 2,
    PIN_VERIFY_RESP_CODE_DEPLETED_ATTEMPS_OUT_OF_RANGE = 3,
    PIN_VERIFY_RESP_CODE_WRONG_PIN = 4,
    PIN_VERIFY_RESP_CODE_FLASH_READ_ERROR = 5,
    PIN_VERIFY_RESP_CODE_FLASH_WRITE_ERROR = 6
} PinVerifyRespCode;

typedef enum _RMemReadRespCode {
    R_MEM_READ_RESP_CODE_UNSPECIFIED = 0,
    R_MEM_READ_RESP_CODE_OK = 1,
    R_MEM_READ_RESP_CODE_ERROR = 2,
    R_MEM_READ_RESP_CODE_SLOT_EMPTY = 3
} RMemReadRespCode;

typedef enum _RMemWriteRespCode {
    R_MEM_WRITE_RESP_CODE_UNSPECIFIED = 0,
    R_MEM_WRITE_RESP_CODE_OK = 1,
    R_MEM_WRITE_RESP_CODE_ERROR = 2,
    R_MEM_WRITE_RESP_CODE_SLOT_NOT_EMPTY = 3
} RMemWriteRespCode;

typedef enum _RMemEraseRespCode {
    R_MEM_ERASE_RESP_CODE_UNSPECIFIED = 0,
    R_MEM_ERASE_RESP_CODE_OK = 1,
    R_MEM_ERASE_RESP_CODE_ERROR = 2
} RMemEraseRespCode;

typedef enum _GetRandBytesRespCode {
    GET_RAND_BYTES_RESP_CODE_UNSPECIFIED = 0,
    GET_RAND_BYTES_RESP_CODE_OK = 1,
    GET_RAND_BYTES_RESP_CODE_ERROR = 2
} GetRandBytesRespCode;

typedef enum _SendSpiDataRespCode {
    SEND_SPI_DATA_RESP_CODE_UNSPECIFIED = 0,
    SEND_SPI_DATA_RESP_CODE_OK = 1,
    SEND_SPI_DATA_RESP_CODE_ERROR = 2,
    SEND_SPI_DATA_RESP_CODE_BUSY = 3,
    SEND_SPI_DATA_RESP_CODE_TIMEOUT = 4
} SendSpiDataRespCode;

typedef enum _SetAutoCsModeRespCode {
    SET_AUTO_CS_MODE_RESP_CODE_UNSPECIFIED = 0,
    SET_AUTO_CS_MODE_RESP_CODE_OK = 1
} SetAutoCsModeRespCode;

typedef enum _SetCsRespCode {
    SET_CS_RESP_CODE_UNSPECIFIED = 0,
    SET_CS_RESP_CODE_OK = 1,
    SET_CS_RESP_CODE_AUTO_CS_MODE_ON = 2
} SetCsRespCode;

typedef enum _SetTr01PwrRespCode {
    SET_TR01_PWR_RESP_CODE_UNSPECIFIED = 0,
    SET_TR01_PWR_RESP_CODE_OK = 1
} SetTr01PwrRespCode;

typedef enum _GetGpoRespCode {
    GET_GPO_RESP_CODE_UNSPECIFIED = 0,
    GET_GPO_RESP_CODE_OK = 1
} GetGpoRespCode;

typedef enum _ErrorRespCode {
    ERROR_RESP_CODE_UNSPECIFIED = 0,
    ERROR_RESP_CODE_BAD_DATA_LEN = 1,
    ERROR_RESP_CODE_BAD_CRC = 2,
    ERROR_RESP_CODE_PB_DECODE = 3,
    ERROR_RESP_CODE_UNKNOWN_CMD = 4
} ErrorRespCode;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(256) PinSetCmd_additional_data_t;
/* ------------------------------- PinSetCmd */
typedef struct _PinSetCmd {
    char new_pin[33];
    uint8_t attempts;
    bool has_additional_data;
    PinSetCmd_additional_data_t additional_data;
    pb_byte_t secret[32];
} PinSetCmd;

typedef PB_BYTES_ARRAY_T(256) PinVerifyCmd_additional_data_t;
/* ------------------------------- PinVerifyCmd */
typedef struct _PinVerifyCmd {
    char pin[33];
    bool has_additional_data;
    PinVerifyCmd_additional_data_t additional_data;
} PinVerifyCmd;

/* ------------------------------- RMemReadCmd */
typedef struct _RMemReadCmd {
    uint16_t udata_slot;
} RMemReadCmd;

typedef PB_BYTES_ARRAY_T(475) RMemWriteCmd_data_t;
/* ------------------------------- RMemWriteCmd */
typedef struct _RMemWriteCmd {
    uint16_t udata_slot;
    RMemWriteCmd_data_t data;
} RMemWriteCmd;

/* ------------------------------- RMemEraseCmd */
typedef struct _RMemEraseCmd {
    uint16_t udata_slot;
} RMemEraseCmd;

/* ------------------------------- GetRandBytesCmd */
typedef struct _GetRandBytesCmd {
    uint8_t count;
} GetRandBytesCmd;

/* ================================= AppCmd ================================== */
typedef struct _AppCmd {
    pb_size_t which_type;
    union {
        PinSetCmd pin_set;
        PinVerifyCmd pin_verify;
        RMemReadCmd r_mem_read;
        RMemWriteCmd r_mem_write;
        RMemEraseCmd r_mem_erase;
        GetRandBytesCmd get_random_bytes;
    } type;
} AppCmd;

/* ------------------------------- PinSetResp */
typedef struct _PinSetResp {
    PinSetRespCode res_code;
    pb_byte_t crypto_key[32];
} PinSetResp;

/* ------------------------------- PinVerifyResp */
typedef struct _PinVerifyResp {
    PinVerifyRespCode res_code;
    pb_byte_t crypto_key[32];
} PinVerifyResp;

typedef PB_BYTES_ARRAY_T(475) RMemReadResp_data_t;
/* ------------------------------- RMemReadResp */
typedef struct _RMemReadResp {
    RMemReadRespCode res_code;
    RMemReadResp_data_t data;
} RMemReadResp;

/* ------------------------------- RMemWriteResp */
typedef struct _RMemWriteResp {
    RMemWriteRespCode res_code;
} RMemWriteResp;

/* ------------------------------- RMemEraseResp */
typedef struct _RMemEraseResp {
    RMemEraseRespCode res_code;
} RMemEraseResp;

typedef PB_BYTES_ARRAY_T(255) GetRandBytesResp_random_bytes_t;
/* ------------------------------- GetRandBytesResp */
typedef struct _GetRandBytesResp {
    GetRandBytesRespCode res_code;
    GetRandBytesResp_random_bytes_t random_bytes;
} GetRandBytesResp;

/* ================================= AppResp ================================= */
typedef struct _AppResp {
    bool has_libtropic_res_code;
    uint32_t libtropic_res_code;
    pb_size_t which_type;
    union {
        PinSetResp pin_set;
        PinVerifyResp pin_verify;
        RMemReadResp r_mem_read;
        RMemWriteResp r_mem_write;
        RMemEraseResp r_mem_erase;
        GetRandBytesResp get_random_bytes;
    } type;
} AppResp;

typedef PB_BYTES_ARRAY_T(257) SendSpiDataCmd_tx_data_t;
/* ------------------------------- SendSpiDataCmd */
typedef struct _SendSpiDataCmd {
    SendSpiDataCmd_tx_data_t tx_data;
    uint32_t timeout_ms;
} SendSpiDataCmd;

/* ------------------------------- SetAutoCsModeCmd */
typedef struct _SetAutoCsModeCmd {
    bool on;
} SetAutoCsModeCmd;

/* ------------------------------- SetCsCmd */
typedef struct _SetCsCmd {
    bool high;
} SetCsCmd;

/* ------------------------------- SetTr01PwrCmd */
typedef struct _SetTr01PwrCmd {
    bool on;
} SetTr01PwrCmd;

/* ------------------------------- GetGpoCmd */
typedef struct _GetGpoCmd { /* Empty command used to read TROPIC01 GPO pin. */
    char dummy_field;
} GetGpoCmd;

/* ================================= RawCmd ================================== */
typedef struct _RawCmd {
    pb_size_t which_type;
    union {
        SendSpiDataCmd send_spi_data;
        SetAutoCsModeCmd set_auto_cs_mode;
        SetCsCmd set_cs;
        SetTr01PwrCmd set_tr01_pwr;
        GetGpoCmd get_gpo;
    } type;
} RawCmd;

/* ============================== UsbDevkitCmd =============================== */
typedef struct _UsbDevkitCmd {
    pb_size_t which_type;
    union {
        AppCmd app;
        RawCmd raw;
    } type;
} UsbDevkitCmd;

typedef PB_BYTES_ARRAY_T(257) SendSpiDataResp_rx_data_t;
/* ------------------------------- SendSpiDataResp */
typedef struct _SendSpiDataResp {
    SendSpiDataRespCode res_code;
    SendSpiDataResp_rx_data_t rx_data;
} SendSpiDataResp;

/* ------------------------------- SetAutoCsModeResp */
typedef struct _SetAutoCsModeResp {
    SetAutoCsModeRespCode res_code;
} SetAutoCsModeResp;

/* ------------------------------- SetCsResp */
typedef struct _SetCsResp {
    SetCsRespCode res_code;
} SetCsResp;

/* ------------------------------- SetTr01PwrResp */
typedef struct _SetTr01PwrResp {
    SetTr01PwrRespCode res_code;
} SetTr01PwrResp;

/* ------------------------------- GetGpoResp */
typedef struct _GetGpoResp {
    GetGpoRespCode res_code;
    bool high;
} GetGpoResp;

/* ================================= RawResp ================================= */
typedef struct _RawResp {
    pb_size_t which_type;
    union {
        SendSpiDataResp send_spi_data;
        SetAutoCsModeResp set_auto_cs_mode;
        SetCsResp set_cs;
        SetTr01PwrResp set_tr01_pwr;
        GetGpoResp get_gpo;
    } type;
} RawResp;

/* ================================ ErrorResp ================================ */
typedef struct _ErrorResp {
    ErrorRespCode res_code;
} ErrorResp;

/* ============================== UsbDevkitResp ============================== */
typedef struct _UsbDevkitResp {
    pb_size_t which_type;
    union {
        AppResp app;
        RawResp raw;
        ErrorResp error;
    } type;
} UsbDevkitResp;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _PinSetRespCode_MIN PIN_SET_RESP_CODE_UNSPECIFIED
#define _PinSetRespCode_MAX PIN_SET_RESP_CODE_KDF_ERROR
#define _PinSetRespCode_ARRAYSIZE ((PinSetRespCode)(PIN_SET_RESP_CODE_KDF_ERROR+1))
#define PinSetRespCode_PIN_SET_RESP_CODE_UNSPECIFIED PIN_SET_RESP_CODE_UNSPECIFIED
#define PinSetRespCode_PIN_SET_RESP_CODE_OK PIN_SET_RESP_CODE_OK
#define PinSetRespCode_PIN_SET_RESP_CODE_ERROR PIN_SET_RESP_CODE_ERROR
#define PinSetRespCode_PIN_SET_RESP_CODE_ATTEMPS_OUT_OF_RANGE PIN_SET_RESP_CODE_ATTEMPS_OUT_OF_RANGE
#define PinSetRespCode_PIN_SET_RESP_CODE_FLASH_WRITE_ERROR PIN_SET_RESP_CODE_FLASH_WRITE_ERROR
#define PinSetRespCode_PIN_SET_RESP_CODE_KDF_ERROR PIN_SET_RESP_CODE_KDF_ERROR

#define _PinVerifyRespCode_MIN PIN_VERIFY_RESP_CODE_UNSPECIFIED
#define _PinVerifyRespCode_MAX PIN_VERIFY_RESP_CODE_FLASH_WRITE_ERROR
#define _PinVerifyRespCode_ARRAYSIZE ((PinVerifyRespCode)(PIN_VERIFY_RESP_CODE_FLASH_WRITE_ERROR+1))
#define PinVerifyRespCode_PIN_VERIFY_RESP_CODE_UNSPECIFIED PIN_VERIFY_RESP_CODE_UNSPECIFIED
#define PinVerifyRespCode_PIN_VERIFY_RESP_CODE_OK PIN_VERIFY_RESP_CODE_OK
#define PinVerifyRespCode_PIN_VERIFY_RESP_CODE_ERROR PIN_VERIFY_RESP_CODE_ERROR
#define PinVerifyRespCode_PIN_VERIFY_RESP_CODE_DEPLETED_ATTEMPS_OUT_OF_RANGE PIN_VERIFY_RESP_CODE_DEPLETED_ATTEMPS_OUT_OF_RANGE
#define PinVerifyRespCode_PIN_VERIFY_RESP_CODE_WRONG_PIN PIN_VERIFY_RESP_CODE_WRONG_PIN
#define PinVerifyRespCode_PIN_VERIFY_RESP_CODE_FLASH_READ_ERROR PIN_VERIFY_RESP_CODE_FLASH_READ_ERROR
#define PinVerifyRespCode_PIN_VERIFY_RESP_CODE_FLASH_WRITE_ERROR PIN_VERIFY_RESP_CODE_FLASH_WRITE_ERROR

#define _RMemReadRespCode_MIN R_MEM_READ_RESP_CODE_UNSPECIFIED
#define _RMemReadRespCode_MAX R_MEM_READ_RESP_CODE_SLOT_EMPTY
#define _RMemReadRespCode_ARRAYSIZE ((RMemReadRespCode)(R_MEM_READ_RESP_CODE_SLOT_EMPTY+1))
#define RMemReadRespCode_R_MEM_READ_RESP_CODE_UNSPECIFIED R_MEM_READ_RESP_CODE_UNSPECIFIED
#define RMemReadRespCode_R_MEM_READ_RESP_CODE_OK R_MEM_READ_RESP_CODE_OK
#define RMemReadRespCode_R_MEM_READ_RESP_CODE_ERROR R_MEM_READ_RESP_CODE_ERROR
#define RMemReadRespCode_R_MEM_READ_RESP_CODE_SLOT_EMPTY R_MEM_READ_RESP_CODE_SLOT_EMPTY

#define _RMemWriteRespCode_MIN R_MEM_WRITE_RESP_CODE_UNSPECIFIED
#define _RMemWriteRespCode_MAX R_MEM_WRITE_RESP_CODE_SLOT_NOT_EMPTY
#define _RMemWriteRespCode_ARRAYSIZE ((RMemWriteRespCode)(R_MEM_WRITE_RESP_CODE_SLOT_NOT_EMPTY+1))
#define RMemWriteRespCode_R_MEM_WRITE_RESP_CODE_UNSPECIFIED R_MEM_WRITE_RESP_CODE_UNSPECIFIED
#define RMemWriteRespCode_R_MEM_WRITE_RESP_CODE_OK R_MEM_WRITE_RESP_CODE_OK
#define RMemWriteRespCode_R_MEM_WRITE_RESP_CODE_ERROR R_MEM_WRITE_RESP_CODE_ERROR
#define RMemWriteRespCode_R_MEM_WRITE_RESP_CODE_SLOT_NOT_EMPTY R_MEM_WRITE_RESP_CODE_SLOT_NOT_EMPTY

#define _RMemEraseRespCode_MIN R_MEM_ERASE_RESP_CODE_UNSPECIFIED
#define _RMemEraseRespCode_MAX R_MEM_ERASE_RESP_CODE_ERROR
#define _RMemEraseRespCode_ARRAYSIZE ((RMemEraseRespCode)(R_MEM_ERASE_RESP_CODE_ERROR+1))
#define RMemEraseRespCode_R_MEM_ERASE_RESP_CODE_UNSPECIFIED R_MEM_ERASE_RESP_CODE_UNSPECIFIED
#define RMemEraseRespCode_R_MEM_ERASE_RESP_CODE_OK R_MEM_ERASE_RESP_CODE_OK
#define RMemEraseRespCode_R_MEM_ERASE_RESP_CODE_ERROR R_MEM_ERASE_RESP_CODE_ERROR

#define _GetRandBytesRespCode_MIN GET_RAND_BYTES_RESP_CODE_UNSPECIFIED
#define _GetRandBytesRespCode_MAX GET_RAND_BYTES_RESP_CODE_ERROR
#define _GetRandBytesRespCode_ARRAYSIZE ((GetRandBytesRespCode)(GET_RAND_BYTES_RESP_CODE_ERROR+1))
#define GetRandBytesRespCode_GET_RAND_BYTES_RESP_CODE_UNSPECIFIED GET_RAND_BYTES_RESP_CODE_UNSPECIFIED
#define GetRandBytesRespCode_GET_RAND_BYTES_RESP_CODE_OK GET_RAND_BYTES_RESP_CODE_OK
#define GetRandBytesRespCode_GET_RAND_BYTES_RESP_CODE_ERROR GET_RAND_BYTES_RESP_CODE_ERROR

#define _SendSpiDataRespCode_MIN SEND_SPI_DATA_RESP_CODE_UNSPECIFIED
#define _SendSpiDataRespCode_MAX SEND_SPI_DATA_RESP_CODE_TIMEOUT
#define _SendSpiDataRespCode_ARRAYSIZE ((SendSpiDataRespCode)(SEND_SPI_DATA_RESP_CODE_TIMEOUT+1))
#define SendSpiDataRespCode_SEND_SPI_DATA_RESP_CODE_UNSPECIFIED SEND_SPI_DATA_RESP_CODE_UNSPECIFIED
#define SendSpiDataRespCode_SEND_SPI_DATA_RESP_CODE_OK SEND_SPI_DATA_RESP_CODE_OK
#define SendSpiDataRespCode_SEND_SPI_DATA_RESP_CODE_ERROR SEND_SPI_DATA_RESP_CODE_ERROR
#define SendSpiDataRespCode_SEND_SPI_DATA_RESP_CODE_BUSY SEND_SPI_DATA_RESP_CODE_BUSY
#define SendSpiDataRespCode_SEND_SPI_DATA_RESP_CODE_TIMEOUT SEND_SPI_DATA_RESP_CODE_TIMEOUT

#define _SetAutoCsModeRespCode_MIN SET_AUTO_CS_MODE_RESP_CODE_UNSPECIFIED
#define _SetAutoCsModeRespCode_MAX SET_AUTO_CS_MODE_RESP_CODE_OK
#define _SetAutoCsModeRespCode_ARRAYSIZE ((SetAutoCsModeRespCode)(SET_AUTO_CS_MODE_RESP_CODE_OK+1))
#define SetAutoCsModeRespCode_SET_AUTO_CS_MODE_RESP_CODE_UNSPECIFIED SET_AUTO_CS_MODE_RESP_CODE_UNSPECIFIED
#define SetAutoCsModeRespCode_SET_AUTO_CS_MODE_RESP_CODE_OK SET_AUTO_CS_MODE_RESP_CODE_OK

#define _SetCsRespCode_MIN SET_CS_RESP_CODE_UNSPECIFIED
#define _SetCsRespCode_MAX SET_CS_RESP_CODE_AUTO_CS_MODE_ON
#define _SetCsRespCode_ARRAYSIZE ((SetCsRespCode)(SET_CS_RESP_CODE_AUTO_CS_MODE_ON+1))
#define SetCsRespCode_SET_CS_RESP_CODE_UNSPECIFIED SET_CS_RESP_CODE_UNSPECIFIED
#define SetCsRespCode_SET_CS_RESP_CODE_OK SET_CS_RESP_CODE_OK
#define SetCsRespCode_SET_CS_RESP_CODE_AUTO_CS_MODE_ON SET_CS_RESP_CODE_AUTO_CS_MODE_ON

#define _SetTr01PwrRespCode_MIN SET_TR01_PWR_RESP_CODE_UNSPECIFIED
#define _SetTr01PwrRespCode_MAX SET_TR01_PWR_RESP_CODE_OK
#define _SetTr01PwrRespCode_ARRAYSIZE ((SetTr01PwrRespCode)(SET_TR01_PWR_RESP_CODE_OK+1))
#define SetTr01PwrRespCode_SET_TR01_PWR_RESP_CODE_UNSPECIFIED SET_TR01_PWR_RESP_CODE_UNSPECIFIED
#define SetTr01PwrRespCode_SET_TR01_PWR_RESP_CODE_OK SET_TR01_PWR_RESP_CODE_OK

#define _GetGpoRespCode_MIN GET_GPO_RESP_CODE_UNSPECIFIED
#define _GetGpoRespCode_MAX GET_GPO_RESP_CODE_OK
#define _GetGpoRespCode_ARRAYSIZE ((GetGpoRespCode)(GET_GPO_RESP_CODE_OK+1))
#define GetGpoRespCode_GET_GPO_RESP_CODE_UNSPECIFIED GET_GPO_RESP_CODE_UNSPECIFIED
#define GetGpoRespCode_GET_GPO_RESP_CODE_OK GET_GPO_RESP_CODE_OK

#define _ErrorRespCode_MIN ERROR_RESP_CODE_UNSPECIFIED
#define _ErrorRespCode_MAX ERROR_RESP_CODE_UNKNOWN_CMD
#define _ErrorRespCode_ARRAYSIZE ((ErrorRespCode)(ERROR_RESP_CODE_UNKNOWN_CMD+1))
#define ErrorRespCode_ERROR_RESP_CODE_UNSPECIFIED ERROR_RESP_CODE_UNSPECIFIED
#define ErrorRespCode_ERROR_RESP_CODE_BAD_DATA_LEN ERROR_RESP_CODE_BAD_DATA_LEN
#define ErrorRespCode_ERROR_RESP_CODE_BAD_CRC ERROR_RESP_CODE_BAD_CRC
#define ErrorRespCode_ERROR_RESP_CODE_PB_DECODE ERROR_RESP_CODE_PB_DECODE
#define ErrorRespCode_ERROR_RESP_CODE_UNKNOWN_CMD ERROR_RESP_CODE_UNKNOWN_CMD











#define PinSetResp_res_code_ENUMTYPE PinSetRespCode

#define PinVerifyResp_res_code_ENUMTYPE PinVerifyRespCode

#define RMemReadResp_res_code_ENUMTYPE RMemReadRespCode

#define RMemWriteResp_res_code_ENUMTYPE RMemWriteRespCode

#define RMemEraseResp_res_code_ENUMTYPE RMemEraseRespCode

#define GetRandBytesResp_res_code_ENUMTYPE GetRandBytesRespCode








#define SendSpiDataResp_res_code_ENUMTYPE SendSpiDataRespCode

#define SetAutoCsModeResp_res_code_ENUMTYPE SetAutoCsModeRespCode

#define SetCsResp_res_code_ENUMTYPE SetCsRespCode

#define SetTr01PwrResp_res_code_ENUMTYPE SetTr01PwrRespCode

#define GetGpoResp_res_code_ENUMTYPE GetGpoRespCode

#define ErrorResp_res_code_ENUMTYPE ErrorRespCode


/* Initializer values for message structs */
#define UsbDevkitCmd_init_default                {0, {AppCmd_init_default}}
#define UsbDevkitResp_init_default               {0, {AppResp_init_default}}
#define AppCmd_init_default                      {0, {PinSetCmd_init_default}}
#define PinSetCmd_init_default                   {"", 0, false, {0, {0}}, {0}}
#define PinVerifyCmd_init_default                {"", false, {0, {0}}}
#define RMemReadCmd_init_default                 {0}
#define RMemWriteCmd_init_default                {0, {0, {0}}}
#define RMemEraseCmd_init_default                {0}
#define GetRandBytesCmd_init_default             {0}
#define AppResp_init_default                     {false, 0, 0, {PinSetResp_init_default}}
#define PinSetResp_init_default                  {_PinSetRespCode_MIN, {0}}
#define PinVerifyResp_init_default               {_PinVerifyRespCode_MIN, {0}}
#define RMemReadResp_init_default                {_RMemReadRespCode_MIN, {0, {0}}}
#define RMemWriteResp_init_default               {_RMemWriteRespCode_MIN}
#define RMemEraseResp_init_default               {_RMemEraseRespCode_MIN}
#define GetRandBytesResp_init_default            {_GetRandBytesRespCode_MIN, {0, {0}}}
#define RawCmd_init_default                      {0, {SendSpiDataCmd_init_default}}
#define SendSpiDataCmd_init_default              {{0, {0}}, 0}
#define SetAutoCsModeCmd_init_default            {0}
#define SetCsCmd_init_default                    {0}
#define SetTr01PwrCmd_init_default               {0}
#define GetGpoCmd_init_default                   {0}
#define RawResp_init_default                     {0, {SendSpiDataResp_init_default}}
#define SendSpiDataResp_init_default             {_SendSpiDataRespCode_MIN, {0, {0}}}
#define SetAutoCsModeResp_init_default           {_SetAutoCsModeRespCode_MIN}
#define SetCsResp_init_default                   {_SetCsRespCode_MIN}
#define SetTr01PwrResp_init_default              {_SetTr01PwrRespCode_MIN}
#define GetGpoResp_init_default                  {_GetGpoRespCode_MIN, 0}
#define ErrorResp_init_default                   {_ErrorRespCode_MIN}
#define UsbDevkitCmd_init_zero                   {0, {AppCmd_init_zero}}
#define UsbDevkitResp_init_zero                  {0, {AppResp_init_zero}}
#define AppCmd_init_zero                         {0, {PinSetCmd_init_zero}}
#define PinSetCmd_init_zero                      {"", 0, false, {0, {0}}, {0}}
#define PinVerifyCmd_init_zero                   {"", false, {0, {0}}}
#define RMemReadCmd_init_zero                    {0}
#define RMemWriteCmd_init_zero                   {0, {0, {0}}}
#define RMemEraseCmd_init_zero                   {0}
#define GetRandBytesCmd_init_zero                {0}
#define AppResp_init_zero                        {false, 0, 0, {PinSetResp_init_zero}}
#define PinSetResp_init_zero                     {_PinSetRespCode_MIN, {0}}
#define PinVerifyResp_init_zero                  {_PinVerifyRespCode_MIN, {0}}
#define RMemReadResp_init_zero                   {_RMemReadRespCode_MIN, {0, {0}}}
#define RMemWriteResp_init_zero                  {_RMemWriteRespCode_MIN}
#define RMemEraseResp_init_zero                  {_RMemEraseRespCode_MIN}
#define GetRandBytesResp_init_zero               {_GetRandBytesRespCode_MIN, {0, {0}}}
#define RawCmd_init_zero                         {0, {SendSpiDataCmd_init_zero}}
#define SendSpiDataCmd_init_zero                 {{0, {0}}, 0}
#define SetAutoCsModeCmd_init_zero               {0}
#define SetCsCmd_init_zero                       {0}
#define SetTr01PwrCmd_init_zero                  {0}
#define GetGpoCmd_init_zero                      {0}
#define RawResp_init_zero                        {0, {SendSpiDataResp_init_zero}}
#define SendSpiDataResp_init_zero                {_SendSpiDataRespCode_MIN, {0, {0}}}
#define SetAutoCsModeResp_init_zero              {_SetAutoCsModeRespCode_MIN}
#define SetCsResp_init_zero                      {_SetCsRespCode_MIN}
#define SetTr01PwrResp_init_zero                 {_SetTr01PwrRespCode_MIN}
#define GetGpoResp_init_zero                     {_GetGpoRespCode_MIN, 0}
#define ErrorResp_init_zero                      {_ErrorRespCode_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define PinSetCmd_new_pin_tag                    1
#define PinSetCmd_attempts_tag                   2
#define PinSetCmd_additional_data_tag            3
#define PinSetCmd_secret_tag                     4
#define PinVerifyCmd_pin_tag                     1
#define PinVerifyCmd_additional_data_tag         2
#define RMemReadCmd_udata_slot_tag               1
#define RMemWriteCmd_udata_slot_tag              1
#define RMemWriteCmd_data_tag                    2
#define RMemEraseCmd_udata_slot_tag              1
#define GetRandBytesCmd_count_tag                1
#define AppCmd_pin_set_tag                       1
#define AppCmd_pin_verify_tag                    2
#define AppCmd_r_mem_read_tag                    3
#define AppCmd_r_mem_write_tag                   4
#define AppCmd_r_mem_erase_tag                   5
#define AppCmd_get_random_bytes_tag              6
#define PinSetResp_res_code_tag                  1
#define PinSetResp_crypto_key_tag                2
#define PinVerifyResp_res_code_tag               1
#define PinVerifyResp_crypto_key_tag             3
#define RMemReadResp_res_code_tag                1
#define RMemReadResp_data_tag                    2
#define RMemWriteResp_res_code_tag               1
#define RMemEraseResp_res_code_tag               1
#define GetRandBytesResp_res_code_tag            1
#define GetRandBytesResp_random_bytes_tag        2
#define AppResp_libtropic_res_code_tag           1
#define AppResp_pin_set_tag                      2
#define AppResp_pin_verify_tag                   3
#define AppResp_r_mem_read_tag                   4
#define AppResp_r_mem_write_tag                  5
#define AppResp_r_mem_erase_tag                  6
#define AppResp_get_random_bytes_tag             7
#define SendSpiDataCmd_tx_data_tag               1
#define SendSpiDataCmd_timeout_ms_tag            2
#define SetAutoCsModeCmd_on_tag                  1
#define SetCsCmd_high_tag                        1
#define SetTr01PwrCmd_on_tag                     1
#define RawCmd_send_spi_data_tag                 1
#define RawCmd_set_auto_cs_mode_tag              2
#define RawCmd_set_cs_tag                        3
#define RawCmd_set_tr01_pwr_tag                  4
#define RawCmd_get_gpo_tag                       5
#define UsbDevkitCmd_app_tag                     1
#define UsbDevkitCmd_raw_tag                     2
#define SendSpiDataResp_res_code_tag             1
#define SendSpiDataResp_rx_data_tag              2
#define SetAutoCsModeResp_res_code_tag           1
#define SetCsResp_res_code_tag                   1
#define SetTr01PwrResp_res_code_tag              1
#define GetGpoResp_res_code_tag                  1
#define GetGpoResp_high_tag                      2
#define RawResp_send_spi_data_tag                1
#define RawResp_set_auto_cs_mode_tag             2
#define RawResp_set_cs_tag                       3
#define RawResp_set_tr01_pwr_tag                 4
#define RawResp_get_gpo_tag                      5
#define ErrorResp_res_code_tag                   1
#define UsbDevkitResp_app_tag                    1
#define UsbDevkitResp_raw_tag                    2
#define UsbDevkitResp_error_tag                  3

/* Struct field encoding specification for nanopb */
#define UsbDevkitCmd_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,app,type.app),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,raw,type.raw),   2)
#define UsbDevkitCmd_CALLBACK NULL
#define UsbDevkitCmd_DEFAULT NULL
#define UsbDevkitCmd_type_app_MSGTYPE AppCmd
#define UsbDevkitCmd_type_raw_MSGTYPE RawCmd

#define UsbDevkitResp_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,app,type.app),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,raw,type.raw),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,error,type.error),   3)
#define UsbDevkitResp_CALLBACK NULL
#define UsbDevkitResp_DEFAULT NULL
#define UsbDevkitResp_type_app_MSGTYPE AppResp
#define UsbDevkitResp_type_raw_MSGTYPE RawResp
#define UsbDevkitResp_type_error_MSGTYPE ErrorResp

#define AppCmd_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,pin_set,type.pin_set),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,pin_verify,type.pin_verify),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,r_mem_read,type.r_mem_read),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,r_mem_write,type.r_mem_write),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,r_mem_erase,type.r_mem_erase),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,get_random_bytes,type.get_random_bytes),   6)
#define AppCmd_CALLBACK NULL
#define AppCmd_DEFAULT NULL
#define AppCmd_type_pin_set_MSGTYPE PinSetCmd
#define AppCmd_type_pin_verify_MSGTYPE PinVerifyCmd
#define AppCmd_type_r_mem_read_MSGTYPE RMemReadCmd
#define AppCmd_type_r_mem_write_MSGTYPE RMemWriteCmd
#define AppCmd_type_r_mem_erase_MSGTYPE RMemEraseCmd
#define AppCmd_type_get_random_bytes_MSGTYPE GetRandBytesCmd

#define PinSetCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   new_pin,           1) \
X(a, STATIC,   SINGULAR, UINT32,   attempts,          2) \
X(a, STATIC,   OPTIONAL, BYTES,    additional_data,   3) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, secret,            4)
#define PinSetCmd_CALLBACK NULL
#define PinSetCmd_DEFAULT NULL

#define PinVerifyCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pin,               1) \
X(a, STATIC,   OPTIONAL, BYTES,    additional_data,   2)
#define PinVerifyCmd_CALLBACK NULL
#define PinVerifyCmd_DEFAULT NULL

#define RMemReadCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   udata_slot,        1)
#define RMemReadCmd_CALLBACK NULL
#define RMemReadCmd_DEFAULT NULL

#define RMemWriteCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   udata_slot,        1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define RMemWriteCmd_CALLBACK NULL
#define RMemWriteCmd_DEFAULT NULL

#define RMemEraseCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   udata_slot,        1)
#define RMemEraseCmd_CALLBACK NULL
#define RMemEraseCmd_DEFAULT NULL

#define GetRandBytesCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   count,             1)
#define GetRandBytesCmd_CALLBACK NULL
#define GetRandBytesCmd_DEFAULT NULL

#define AppResp_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   libtropic_res_code,   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,pin_set,type.pin_set),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,pin_verify,type.pin_verify),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,r_mem_read,type.r_mem_read),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,r_mem_write,type.r_mem_write),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,r_mem_erase,type.r_mem_erase),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,get_random_bytes,type.get_random_bytes),   7)
#define AppResp_CALLBACK NULL
#define AppResp_DEFAULT NULL
#define AppResp_type_pin_set_MSGTYPE PinSetResp
#define AppResp_type_pin_verify_MSGTYPE PinVerifyResp
#define AppResp_type_r_mem_read_MSGTYPE RMemReadResp
#define AppResp_type_r_mem_write_MSGTYPE RMemWriteResp
#define AppResp_type_r_mem_erase_MSGTYPE RMemEraseResp
#define AppResp_type_get_random_bytes_MSGTYPE GetRandBytesResp

#define PinSetResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    res_code,          1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, crypto_key,        2)
#define PinSetResp_CALLBACK NULL
#define PinSetResp_DEFAULT NULL

#define PinVerifyResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    res_code,          1) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, crypto_key,        3)
#define PinVerifyResp_CALLBACK NULL
#define PinVerifyResp_DEFAULT NULL

#define RMemReadResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    res_code,          1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define RMemReadResp_CALLBACK NULL
#define RMemReadResp_DEFAULT NULL

#define RMemWriteResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    res_code,          1)
#define RMemWriteResp_CALLBACK NULL
#define RMemWriteResp_DEFAULT NULL

#define RMemEraseResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    res_code,          1)
#define RMemEraseResp_CALLBACK NULL
#define RMemEraseResp_DEFAULT NULL

#define GetRandBytesResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    res_code,          1) \
X(a, STATIC,   SINGULAR, BYTES,    random_bytes,      2)
#define GetRandBytesResp_CALLBACK NULL
#define GetRandBytesResp_DEFAULT NULL

#define RawCmd_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,send_spi_data,type.send_spi_data),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,set_auto_cs_mode,type.set_auto_cs_mode),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,set_cs,type.set_cs),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,set_tr01_pwr,type.set_tr01_pwr),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,get_gpo,type.get_gpo),   5)
#define RawCmd_CALLBACK NULL
#define RawCmd_DEFAULT NULL
#define RawCmd_type_send_spi_data_MSGTYPE SendSpiDataCmd
#define RawCmd_type_set_auto_cs_mode_MSGTYPE SetAutoCsModeCmd
#define RawCmd_type_set_cs_MSGTYPE SetCsCmd
#define RawCmd_type_set_tr01_pwr_MSGTYPE SetTr01PwrCmd
#define RawCmd_type_get_gpo_MSGTYPE GetGpoCmd

#define SendSpiDataCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    tx_data,           1) \
X(a, STATIC,   SINGULAR, UINT32,   timeout_ms,        2)
#define SendSpiDataCmd_CALLBACK NULL
#define SendSpiDataCmd_DEFAULT NULL

#define SetAutoCsModeCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     on,                1)
#define SetAutoCsModeCmd_CALLBACK NULL
#define SetAutoCsModeCmd_DEFAULT NULL

#define SetCsCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     high,              1)
#define SetCsCmd_CALLBACK NULL
#define SetCsCmd_DEFAULT NULL

#define SetTr01PwrCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     on,                1)
#define SetTr01PwrCmd_CALLBACK NULL
#define SetTr01PwrCmd_DEFAULT NULL

#define GetGpoCmd_FIELDLIST(X, a) \

#define GetGpoCmd_CALLBACK NULL
#define GetGpoCmd_DEFAULT NULL

#define RawResp_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,send_spi_data,type.send_spi_data),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,set_auto_cs_mode,type.set_auto_cs_mode),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,set_cs,type.set_cs),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,set_tr01_pwr,type.set_tr01_pwr),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (type,get_gpo,type.get_gpo),   5)
#define RawResp_CALLBACK NULL
#define RawResp_DEFAULT NULL
#define RawResp_type_send_spi_data_MSGTYPE SendSpiDataResp
#define RawResp_type_set_auto_cs_mode_MSGTYPE SetAutoCsModeResp
#define RawResp_type_set_cs_MSGTYPE SetCsResp
#define RawResp_type_set_tr01_pwr_MSGTYPE SetTr01PwrResp
#define RawResp_type_get_gpo_MSGTYPE GetGpoResp

#define SendSpiDataResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    res_code,          1) \
X(a, STATIC,   SINGULAR, BYTES,    rx_data,           2)
#define SendSpiDataResp_CALLBACK NULL
#define SendSpiDataResp_DEFAULT NULL

#define SetAutoCsModeResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    res_code,          1)
#define SetAutoCsModeResp_CALLBACK NULL
#define SetAutoCsModeResp_DEFAULT NULL

#define SetCsResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    res_code,          1)
#define SetCsResp_CALLBACK NULL
#define SetCsResp_DEFAULT NULL

#define SetTr01PwrResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    res_code,          1)
#define SetTr01PwrResp_CALLBACK NULL
#define SetTr01PwrResp_DEFAULT NULL

#define GetGpoResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    res_code,          1) \
X(a, STATIC,   SINGULAR, BOOL,     high,              2)
#define GetGpoResp_CALLBACK NULL
#define GetGpoResp_DEFAULT NULL

#define ErrorResp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    res_code,          1)
#define ErrorResp_CALLBACK NULL
#define ErrorResp_DEFAULT NULL

extern const pb_msgdesc_t UsbDevkitCmd_msg;
extern const pb_msgdesc_t UsbDevkitResp_msg;
extern const pb_msgdesc_t AppCmd_msg;
extern const pb_msgdesc_t PinSetCmd_msg;
extern const pb_msgdesc_t PinVerifyCmd_msg;
extern const pb_msgdesc_t RMemReadCmd_msg;
extern const pb_msgdesc_t RMemWriteCmd_msg;
extern const pb_msgdesc_t RMemEraseCmd_msg;
extern const pb_msgdesc_t GetRandBytesCmd_msg;
extern const pb_msgdesc_t AppResp_msg;
extern const pb_msgdesc_t PinSetResp_msg;
extern const pb_msgdesc_t PinVerifyResp_msg;
extern const pb_msgdesc_t RMemReadResp_msg;
extern const pb_msgdesc_t RMemWriteResp_msg;
extern const pb_msgdesc_t RMemEraseResp_msg;
extern const pb_msgdesc_t GetRandBytesResp_msg;
extern const pb_msgdesc_t RawCmd_msg;
extern const pb_msgdesc_t SendSpiDataCmd_msg;
extern const pb_msgdesc_t SetAutoCsModeCmd_msg;
extern const pb_msgdesc_t SetCsCmd_msg;
extern const pb_msgdesc_t SetTr01PwrCmd_msg;
extern const pb_msgdesc_t GetGpoCmd_msg;
extern const pb_msgdesc_t RawResp_msg;
extern const pb_msgdesc_t SendSpiDataResp_msg;
extern const pb_msgdesc_t SetAutoCsModeResp_msg;
extern const pb_msgdesc_t SetCsResp_msg;
extern const pb_msgdesc_t SetTr01PwrResp_msg;
extern const pb_msgdesc_t GetGpoResp_msg;
extern const pb_msgdesc_t ErrorResp_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UsbDevkitCmd_fields &UsbDevkitCmd_msg
#define UsbDevkitResp_fields &UsbDevkitResp_msg
#define AppCmd_fields &AppCmd_msg
#define PinSetCmd_fields &PinSetCmd_msg
#define PinVerifyCmd_fields &PinVerifyCmd_msg
#define RMemReadCmd_fields &RMemReadCmd_msg
#define RMemWriteCmd_fields &RMemWriteCmd_msg
#define RMemEraseCmd_fields &RMemEraseCmd_msg
#define GetRandBytesCmd_fields &GetRandBytesCmd_msg
#define AppResp_fields &AppResp_msg
#define PinSetResp_fields &PinSetResp_msg
#define PinVerifyResp_fields &PinVerifyResp_msg
#define RMemReadResp_fields &RMemReadResp_msg
#define RMemWriteResp_fields &RMemWriteResp_msg
#define RMemEraseResp_fields &RMemEraseResp_msg
#define GetRandBytesResp_fields &GetRandBytesResp_msg
#define RawCmd_fields &RawCmd_msg
#define SendSpiDataCmd_fields &SendSpiDataCmd_msg
#define SetAutoCsModeCmd_fields &SetAutoCsModeCmd_msg
#define SetCsCmd_fields &SetCsCmd_msg
#define SetTr01PwrCmd_fields &SetTr01PwrCmd_msg
#define GetGpoCmd_fields &GetGpoCmd_msg
#define RawResp_fields &RawResp_msg
#define SendSpiDataResp_fields &SendSpiDataResp_msg
#define SetAutoCsModeResp_fields &SetAutoCsModeResp_msg
#define SetCsResp_fields &SetCsResp_msg
#define SetTr01PwrResp_fields &SetTr01PwrResp_msg
#define GetGpoResp_fields &GetGpoResp_msg
#define ErrorResp_fields &ErrorResp_msg

/* Maximum encoded size of messages (where known) */
#define AppCmd_size                              485
#define AppResp_size                             489
#define ErrorResp_size                           2
#define GetGpoCmd_size                           0
#define GetGpoResp_size                          4
#define GetRandBytesCmd_size                     3
#define GetRandBytesResp_size                    260
#define PinSetCmd_size                           330
#define PinSetResp_size                          36
#define PinVerifyCmd_size                        293
#define PinVerifyResp_size                       36
#define RMemEraseCmd_size                        4
#define RMemEraseResp_size                       2
#define RMemReadCmd_size                         4
#define RMemReadResp_size                        480
#define RMemWriteCmd_size                        482
#define RMemWriteResp_size                       2
#define RawCmd_size                              269
#define RawResp_size                             265
#define SendSpiDataCmd_size                      266
#define SendSpiDataResp_size                     262
#define SetAutoCsModeCmd_size                    2
#define SetAutoCsModeResp_size                   2
#define SetCsCmd_size                            2
#define SetCsResp_size                           2
#define SetTr01PwrCmd_size                       2
#define SetTr01PwrResp_size                      2
#define USB_DEVKIT_MESSAGES_PB_H_MAX_SIZE        UsbDevkitResp_size
#define UsbDevkitCmd_size                        488
#define UsbDevkitResp_size                       492

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
