"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _PinSetRespCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PinSetRespCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PinSetRespCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PIN_SET_RESP_CODE_UNSPECIFIED: _PinSetRespCode.ValueType  # 0
    PIN_SET_RESP_CODE_OK: _PinSetRespCode.ValueType  # 1
    PIN_SET_RESP_CODE_ERROR: _PinSetRespCode.ValueType  # 2
    PIN_SET_RESP_CODE_ATTEMPS_OUT_OF_RANGE: _PinSetRespCode.ValueType  # 3
    PIN_SET_RESP_CODE_FLASH_WRITE_ERROR: _PinSetRespCode.ValueType  # 4

class PinSetRespCode(_PinSetRespCode, metaclass=_PinSetRespCodeEnumTypeWrapper): ...

PIN_SET_RESP_CODE_UNSPECIFIED: PinSetRespCode.ValueType  # 0
PIN_SET_RESP_CODE_OK: PinSetRespCode.ValueType  # 1
PIN_SET_RESP_CODE_ERROR: PinSetRespCode.ValueType  # 2
PIN_SET_RESP_CODE_ATTEMPS_OUT_OF_RANGE: PinSetRespCode.ValueType  # 3
PIN_SET_RESP_CODE_FLASH_WRITE_ERROR: PinSetRespCode.ValueType  # 4
Global___PinSetRespCode: _TypeAlias = PinSetRespCode  # noqa: Y015

class _PinVerifyRespCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PinVerifyRespCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PinVerifyRespCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PIN_VERIFY_RESP_CODE_UNSPECIFIED: _PinVerifyRespCode.ValueType  # 0
    PIN_VERIFY_RESP_CODE_OK: _PinVerifyRespCode.ValueType  # 1
    PIN_VERIFY_RESP_CODE_ERROR: _PinVerifyRespCode.ValueType  # 2
    PIN_VERIFY_RESP_CODE_DEPLETED_ATTEMPS_OUT_OF_RANGE: _PinVerifyRespCode.ValueType  # 3
    PIN_VERIFY_RESP_CODE_WRONG_PIN: _PinVerifyRespCode.ValueType  # 4
    PIN_VERIFY_RESP_CODE_FLASH_READ_ERROR: _PinVerifyRespCode.ValueType  # 5
    PIN_VERIFY_RESP_CODE_FLASH_WRITE_ERROR: _PinVerifyRespCode.ValueType  # 6

class PinVerifyRespCode(_PinVerifyRespCode, metaclass=_PinVerifyRespCodeEnumTypeWrapper): ...

PIN_VERIFY_RESP_CODE_UNSPECIFIED: PinVerifyRespCode.ValueType  # 0
PIN_VERIFY_RESP_CODE_OK: PinVerifyRespCode.ValueType  # 1
PIN_VERIFY_RESP_CODE_ERROR: PinVerifyRespCode.ValueType  # 2
PIN_VERIFY_RESP_CODE_DEPLETED_ATTEMPS_OUT_OF_RANGE: PinVerifyRespCode.ValueType  # 3
PIN_VERIFY_RESP_CODE_WRONG_PIN: PinVerifyRespCode.ValueType  # 4
PIN_VERIFY_RESP_CODE_FLASH_READ_ERROR: PinVerifyRespCode.ValueType  # 5
PIN_VERIFY_RESP_CODE_FLASH_WRITE_ERROR: PinVerifyRespCode.ValueType  # 6
Global___PinVerifyRespCode: _TypeAlias = PinVerifyRespCode  # noqa: Y015

class _RMemReadRespCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RMemReadRespCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RMemReadRespCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    R_MEM_READ_RESP_CODE_UNSPECIFIED: _RMemReadRespCode.ValueType  # 0
    R_MEM_READ_RESP_CODE_OK: _RMemReadRespCode.ValueType  # 1
    R_MEM_READ_RESP_CODE_ERROR: _RMemReadRespCode.ValueType  # 2

class RMemReadRespCode(_RMemReadRespCode, metaclass=_RMemReadRespCodeEnumTypeWrapper): ...

R_MEM_READ_RESP_CODE_UNSPECIFIED: RMemReadRespCode.ValueType  # 0
R_MEM_READ_RESP_CODE_OK: RMemReadRespCode.ValueType  # 1
R_MEM_READ_RESP_CODE_ERROR: RMemReadRespCode.ValueType  # 2
Global___RMemReadRespCode: _TypeAlias = RMemReadRespCode  # noqa: Y015

class _RMemWriteRespCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RMemWriteRespCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RMemWriteRespCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    R_MEM_WRITE_RESP_CODE_UNSPECIFIED: _RMemWriteRespCode.ValueType  # 0
    R_MEM_WRITE_RESP_CODE_OK: _RMemWriteRespCode.ValueType  # 1
    R_MEM_WRITE_RESP_CODE_ERROR: _RMemWriteRespCode.ValueType  # 2

class RMemWriteRespCode(_RMemWriteRespCode, metaclass=_RMemWriteRespCodeEnumTypeWrapper): ...

R_MEM_WRITE_RESP_CODE_UNSPECIFIED: RMemWriteRespCode.ValueType  # 0
R_MEM_WRITE_RESP_CODE_OK: RMemWriteRespCode.ValueType  # 1
R_MEM_WRITE_RESP_CODE_ERROR: RMemWriteRespCode.ValueType  # 2
Global___RMemWriteRespCode: _TypeAlias = RMemWriteRespCode  # noqa: Y015

class _SendSpiDataRespCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SendSpiDataRespCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SendSpiDataRespCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SEND_SPI_DATA_RESP_CODE_UNSPECIFIED: _SendSpiDataRespCode.ValueType  # 0
    SEND_SPI_DATA_RESP_CODE_OK: _SendSpiDataRespCode.ValueType  # 1
    SEND_SPI_DATA_RESP_CODE_ERROR: _SendSpiDataRespCode.ValueType  # 2
    SEND_SPI_DATA_RESP_CODE_BUSY: _SendSpiDataRespCode.ValueType  # 3
    SEND_SPI_DATA_RESP_CODE_TIMEOUT: _SendSpiDataRespCode.ValueType  # 4

class SendSpiDataRespCode(_SendSpiDataRespCode, metaclass=_SendSpiDataRespCodeEnumTypeWrapper): ...

SEND_SPI_DATA_RESP_CODE_UNSPECIFIED: SendSpiDataRespCode.ValueType  # 0
SEND_SPI_DATA_RESP_CODE_OK: SendSpiDataRespCode.ValueType  # 1
SEND_SPI_DATA_RESP_CODE_ERROR: SendSpiDataRespCode.ValueType  # 2
SEND_SPI_DATA_RESP_CODE_BUSY: SendSpiDataRespCode.ValueType  # 3
SEND_SPI_DATA_RESP_CODE_TIMEOUT: SendSpiDataRespCode.ValueType  # 4
Global___SendSpiDataRespCode: _TypeAlias = SendSpiDataRespCode  # noqa: Y015

class _SetAutoCsModeRespCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SetAutoCsModeRespCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SetAutoCsModeRespCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SET_AUTO_CS_MODE_RESP_CODE_UNSPECIFIED: _SetAutoCsModeRespCode.ValueType  # 0
    SET_AUTO_CS_MODE_RESP_CODE_OK: _SetAutoCsModeRespCode.ValueType  # 1

class SetAutoCsModeRespCode(_SetAutoCsModeRespCode, metaclass=_SetAutoCsModeRespCodeEnumTypeWrapper): ...

SET_AUTO_CS_MODE_RESP_CODE_UNSPECIFIED: SetAutoCsModeRespCode.ValueType  # 0
SET_AUTO_CS_MODE_RESP_CODE_OK: SetAutoCsModeRespCode.ValueType  # 1
Global___SetAutoCsModeRespCode: _TypeAlias = SetAutoCsModeRespCode  # noqa: Y015

class _SetCsRespCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SetCsRespCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SetCsRespCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SET_CS_RESP_CODE_UNSPECIFIED: _SetCsRespCode.ValueType  # 0
    SET_CS_RESP_CODE_OK: _SetCsRespCode.ValueType  # 1
    SET_CS_RESP_CODE_AUTO_CS_MODE_ON: _SetCsRespCode.ValueType  # 2

class SetCsRespCode(_SetCsRespCode, metaclass=_SetCsRespCodeEnumTypeWrapper): ...

SET_CS_RESP_CODE_UNSPECIFIED: SetCsRespCode.ValueType  # 0
SET_CS_RESP_CODE_OK: SetCsRespCode.ValueType  # 1
SET_CS_RESP_CODE_AUTO_CS_MODE_ON: SetCsRespCode.ValueType  # 2
Global___SetCsRespCode: _TypeAlias = SetCsRespCode  # noqa: Y015

class _SetTr01PwrRespCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SetTr01PwrRespCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SetTr01PwrRespCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SET_TR01_PWR_RESP_CODE_UNSPECIFIED: _SetTr01PwrRespCode.ValueType  # 0
    SET_TR01_PWR_RESP_CODE_OK: _SetTr01PwrRespCode.ValueType  # 1

class SetTr01PwrRespCode(_SetTr01PwrRespCode, metaclass=_SetTr01PwrRespCodeEnumTypeWrapper): ...

SET_TR01_PWR_RESP_CODE_UNSPECIFIED: SetTr01PwrRespCode.ValueType  # 0
SET_TR01_PWR_RESP_CODE_OK: SetTr01PwrRespCode.ValueType  # 1
Global___SetTr01PwrRespCode: _TypeAlias = SetTr01PwrRespCode  # noqa: Y015

class _GetGpoRespCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _GetGpoRespCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_GetGpoRespCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GET_GPO_RESP_CODE_UNSPECIFIED: _GetGpoRespCode.ValueType  # 0
    GET_GPO_RESP_CODE_OK: _GetGpoRespCode.ValueType  # 1

class GetGpoRespCode(_GetGpoRespCode, metaclass=_GetGpoRespCodeEnumTypeWrapper): ...

GET_GPO_RESP_CODE_UNSPECIFIED: GetGpoRespCode.ValueType  # 0
GET_GPO_RESP_CODE_OK: GetGpoRespCode.ValueType  # 1
Global___GetGpoRespCode: _TypeAlias = GetGpoRespCode  # noqa: Y015

class _ErrorRespCode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ErrorRespCodeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ErrorRespCode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ERROR_RESP_CODE_UNSPECIFIED: _ErrorRespCode.ValueType  # 0
    ERROR_RESP_CODE_BAD_DATA_LEN: _ErrorRespCode.ValueType  # 1
    ERROR_RESP_CODE_BAD_CRC: _ErrorRespCode.ValueType  # 2
    ERROR_RESP_CODE_PB_DECODE: _ErrorRespCode.ValueType  # 3
    ERROR_RESP_CODE_UNKNOWN_CMD: _ErrorRespCode.ValueType  # 4

class ErrorRespCode(_ErrorRespCode, metaclass=_ErrorRespCodeEnumTypeWrapper): ...

ERROR_RESP_CODE_UNSPECIFIED: ErrorRespCode.ValueType  # 0
ERROR_RESP_CODE_BAD_DATA_LEN: ErrorRespCode.ValueType  # 1
ERROR_RESP_CODE_BAD_CRC: ErrorRespCode.ValueType  # 2
ERROR_RESP_CODE_PB_DECODE: ErrorRespCode.ValueType  # 3
ERROR_RESP_CODE_UNKNOWN_CMD: ErrorRespCode.ValueType  # 4
Global___ErrorRespCode: _TypeAlias = ErrorRespCode  # noqa: Y015

@_typing.final
class UsbDevkitCmd(_message.Message):
    """============================== UsbDevkitCmd ==============================="""

    DESCRIPTOR: _descriptor.Descriptor

    APP_FIELD_NUMBER: _builtins.int
    RAW_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def app(self) -> Global___AppCmd: ...
    @_builtins.property
    def raw(self) -> Global___RawCmd: ...
    def __init__(
        self,
        *,
        app: Global___AppCmd | None = ...,
        raw: Global___RawCmd | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app", b"app", "raw", b"raw", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app", b"app", "raw", b"raw", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_type: _TypeAlias = _typing.Literal["app", "raw"]  # noqa: Y015
    _WhichOneofArgType_type: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_type) -> _WhichOneofReturnType_type | None: ...

Global___UsbDevkitCmd: _TypeAlias = UsbDevkitCmd  # noqa: Y015

@_typing.final
class UsbDevkitResp(_message.Message):
    """============================== UsbDevkitResp =============================="""

    DESCRIPTOR: _descriptor.Descriptor

    APP_FIELD_NUMBER: _builtins.int
    RAW_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def app(self) -> Global___AppResp: ...
    @_builtins.property
    def raw(self) -> Global___RawResp: ...
    @_builtins.property
    def error(self) -> Global___ErrorResp: ...
    def __init__(
        self,
        *,
        app: Global___AppResp | None = ...,
        raw: Global___RawResp | None = ...,
        error: Global___ErrorResp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["app", b"app", "error", b"error", "raw", b"raw", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app", b"app", "error", b"error", "raw", b"raw", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_type: _TypeAlias = _typing.Literal["app", "raw", "error"]  # noqa: Y015
    _WhichOneofArgType_type: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_type) -> _WhichOneofReturnType_type | None: ...

Global___UsbDevkitResp: _TypeAlias = UsbDevkitResp  # noqa: Y015

@_typing.final
class AppCmd(_message.Message):
    """================================= AppCmd =================================="""

    DESCRIPTOR: _descriptor.Descriptor

    PIN_SET_FIELD_NUMBER: _builtins.int
    PIN_VERIFY_FIELD_NUMBER: _builtins.int
    R_MEM_READ_FIELD_NUMBER: _builtins.int
    R_MEM_WRITE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pin_set(self) -> Global___PinSetCmd: ...
    @_builtins.property
    def pin_verify(self) -> Global___PinVerifyCmd: ...
    @_builtins.property
    def r_mem_read(self) -> Global___RMemReadCmd: ...
    @_builtins.property
    def r_mem_write(self) -> Global___RMemWriteCmd: ...
    def __init__(
        self,
        *,
        pin_set: Global___PinSetCmd | None = ...,
        pin_verify: Global___PinVerifyCmd | None = ...,
        r_mem_read: Global___RMemReadCmd | None = ...,
        r_mem_write: Global___RMemWriteCmd | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pin_set", b"pin_set", "pin_verify", b"pin_verify", "r_mem_read", b"r_mem_read", "r_mem_write", b"r_mem_write", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pin_set", b"pin_set", "pin_verify", b"pin_verify", "r_mem_read", b"r_mem_read", "r_mem_write", b"r_mem_write", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_type: _TypeAlias = _typing.Literal["pin_set", "pin_verify", "r_mem_read", "r_mem_write"]  # noqa: Y015
    _WhichOneofArgType_type: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_type) -> _WhichOneofReturnType_type | None: ...

Global___AppCmd: _TypeAlias = AppCmd  # noqa: Y015

@_typing.final
class PinSetCmd(_message.Message):
    """------------------------------- PinSetCmd"""

    DESCRIPTOR: _descriptor.Descriptor

    NEW_PIN_FIELD_NUMBER: _builtins.int
    ATTEMPTS_FIELD_NUMBER: _builtins.int
    ADDITIONAL_DATA_FIELD_NUMBER: _builtins.int
    SECRET_FIELD_NUMBER: _builtins.int
    new_pin: _builtins.str
    attempts: _builtins.int
    additional_data: _builtins.bytes
    secret: _builtins.bytes
    def __init__(
        self,
        *,
        new_pin: _builtins.str = ...,
        attempts: _builtins.int = ...,
        additional_data: _builtins.bytes | None = ...,
        secret: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_additional_data", b"_additional_data", "additional_data", b"additional_data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_additional_data", b"_additional_data", "additional_data", b"additional_data", "attempts", b"attempts", "new_pin", b"new_pin", "secret", b"secret"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__additional_data: _TypeAlias = _typing.Literal["additional_data"]  # noqa: Y015
    _WhichOneofArgType__additional_data: _TypeAlias = _typing.Literal["_additional_data", b"_additional_data"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__additional_data) -> _WhichOneofReturnType__additional_data | None: ...

Global___PinSetCmd: _TypeAlias = PinSetCmd  # noqa: Y015

@_typing.final
class PinVerifyCmd(_message.Message):
    """------------------------------- PinVerifyCmd"""

    DESCRIPTOR: _descriptor.Descriptor

    PIN_FIELD_NUMBER: _builtins.int
    ADDITIONAL_DATA_FIELD_NUMBER: _builtins.int
    pin: _builtins.str
    additional_data: _builtins.bytes
    def __init__(
        self,
        *,
        pin: _builtins.str = ...,
        additional_data: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_additional_data", b"_additional_data", "additional_data", b"additional_data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_additional_data", b"_additional_data", "additional_data", b"additional_data", "pin", b"pin"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__additional_data: _TypeAlias = _typing.Literal["additional_data"]  # noqa: Y015
    _WhichOneofArgType__additional_data: _TypeAlias = _typing.Literal["_additional_data", b"_additional_data"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__additional_data) -> _WhichOneofReturnType__additional_data | None: ...

Global___PinVerifyCmd: _TypeAlias = PinVerifyCmd  # noqa: Y015

@_typing.final
class RMemReadCmd(_message.Message):
    """------------------------------- RMemReadCmd"""

    DESCRIPTOR: _descriptor.Descriptor

    UDATA_SLOT_FIELD_NUMBER: _builtins.int
    udata_slot: _builtins.int
    def __init__(
        self,
        *,
        udata_slot: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["udata_slot", b"udata_slot"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RMemReadCmd: _TypeAlias = RMemReadCmd  # noqa: Y015

@_typing.final
class RMemWriteCmd(_message.Message):
    """------------------------------- RMemWriteCmd"""

    DESCRIPTOR: _descriptor.Descriptor

    UDATA_SLOT_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    udata_slot: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        udata_slot: _builtins.int = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "udata_slot", b"udata_slot"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RMemWriteCmd: _TypeAlias = RMemWriteCmd  # noqa: Y015

@_typing.final
class AppResp(_message.Message):
    """================================= AppResp ================================="""

    DESCRIPTOR: _descriptor.Descriptor

    PIN_SET_FIELD_NUMBER: _builtins.int
    PIN_VERIFY_FIELD_NUMBER: _builtins.int
    R_MEM_READ_FIELD_NUMBER: _builtins.int
    R_MEM_WRITE_FIELD_NUMBER: _builtins.int
    LIBTROPIC_ERROR_CODE_FIELD_NUMBER: _builtins.int
    libtropic_error_code: _builtins.int
    @_builtins.property
    def pin_set(self) -> Global___PinSetResp: ...
    @_builtins.property
    def pin_verify(self) -> Global___PinVerifyResp: ...
    @_builtins.property
    def r_mem_read(self) -> Global___RMemReadResp: ...
    @_builtins.property
    def r_mem_write(self) -> Global___RMemWriteResp: ...
    def __init__(
        self,
        *,
        pin_set: Global___PinSetResp | None = ...,
        pin_verify: Global___PinVerifyResp | None = ...,
        r_mem_read: Global___RMemReadResp | None = ...,
        r_mem_write: Global___RMemWriteResp | None = ...,
        libtropic_error_code: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_libtropic_error_code", b"_libtropic_error_code", "libtropic_error_code", b"libtropic_error_code", "pin_set", b"pin_set", "pin_verify", b"pin_verify", "r_mem_read", b"r_mem_read", "r_mem_write", b"r_mem_write", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_libtropic_error_code", b"_libtropic_error_code", "libtropic_error_code", b"libtropic_error_code", "pin_set", b"pin_set", "pin_verify", b"pin_verify", "r_mem_read", b"r_mem_read", "r_mem_write", b"r_mem_write", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__libtropic_error_code: _TypeAlias = _typing.Literal["libtropic_error_code"]  # noqa: Y015
    _WhichOneofArgType__libtropic_error_code: _TypeAlias = _typing.Literal["_libtropic_error_code", b"_libtropic_error_code"]  # noqa: Y015
    _WhichOneofReturnType_type: _TypeAlias = _typing.Literal["pin_set", "pin_verify", "r_mem_read", "r_mem_write"]  # noqa: Y015
    _WhichOneofArgType_type: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__libtropic_error_code) -> _WhichOneofReturnType__libtropic_error_code | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType_type) -> _WhichOneofReturnType_type | None: ...

Global___AppResp: _TypeAlias = AppResp  # noqa: Y015

@_typing.final
class PinSetResp(_message.Message):
    """------------------------------- PinSetResp"""

    DESCRIPTOR: _descriptor.Descriptor

    RES_CODE_FIELD_NUMBER: _builtins.int
    CRYPTO_KEY_FIELD_NUMBER: _builtins.int
    res_code: Global___PinSetRespCode.ValueType
    crypto_key: _builtins.bytes
    def __init__(
        self,
        *,
        res_code: Global___PinSetRespCode.ValueType = ...,
        crypto_key: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["crypto_key", b"crypto_key", "res_code", b"res_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PinSetResp: _TypeAlias = PinSetResp  # noqa: Y015

@_typing.final
class PinVerifyResp(_message.Message):
    """------------------------------- PinVerifyResp"""

    DESCRIPTOR: _descriptor.Descriptor

    RES_CODE_FIELD_NUMBER: _builtins.int
    CRYPTO_KEY_FIELD_NUMBER: _builtins.int
    res_code: Global___PinVerifyRespCode.ValueType
    crypto_key: _builtins.bytes
    def __init__(
        self,
        *,
        res_code: Global___PinVerifyRespCode.ValueType = ...,
        crypto_key: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["crypto_key", b"crypto_key", "res_code", b"res_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PinVerifyResp: _TypeAlias = PinVerifyResp  # noqa: Y015

@_typing.final
class RMemReadResp(_message.Message):
    """------------------------------- RMemReadResp"""

    DESCRIPTOR: _descriptor.Descriptor

    RES_CODE_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    res_code: Global___RMemReadRespCode.ValueType
    data: _builtins.bytes
    def __init__(
        self,
        *,
        res_code: Global___RMemReadRespCode.ValueType = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "res_code", b"res_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RMemReadResp: _TypeAlias = RMemReadResp  # noqa: Y015

@_typing.final
class RMemWriteResp(_message.Message):
    """------------------------------- RMemWriteResp"""

    DESCRIPTOR: _descriptor.Descriptor

    RES_CODE_FIELD_NUMBER: _builtins.int
    res_code: Global___RMemWriteRespCode.ValueType
    def __init__(
        self,
        *,
        res_code: Global___RMemWriteRespCode.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["res_code", b"res_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___RMemWriteResp: _TypeAlias = RMemWriteResp  # noqa: Y015

@_typing.final
class RawCmd(_message.Message):
    """================================= RawCmd =================================="""

    DESCRIPTOR: _descriptor.Descriptor

    SEND_SPI_DATA_FIELD_NUMBER: _builtins.int
    SET_AUTO_CS_MODE_FIELD_NUMBER: _builtins.int
    SET_CS_FIELD_NUMBER: _builtins.int
    SET_TR01_PWR_FIELD_NUMBER: _builtins.int
    GET_GPO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def send_spi_data(self) -> Global___SendSpiDataCmd: ...
    @_builtins.property
    def set_auto_cs_mode(self) -> Global___SetAutoCsModeCmd: ...
    @_builtins.property
    def set_cs(self) -> Global___SetCsCmd: ...
    @_builtins.property
    def set_tr01_pwr(self) -> Global___SetTr01PwrCmd: ...
    @_builtins.property
    def get_gpo(self) -> Global___GetGpoCmd: ...
    def __init__(
        self,
        *,
        send_spi_data: Global___SendSpiDataCmd | None = ...,
        set_auto_cs_mode: Global___SetAutoCsModeCmd | None = ...,
        set_cs: Global___SetCsCmd | None = ...,
        set_tr01_pwr: Global___SetTr01PwrCmd | None = ...,
        get_gpo: Global___GetGpoCmd | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["get_gpo", b"get_gpo", "send_spi_data", b"send_spi_data", "set_auto_cs_mode", b"set_auto_cs_mode", "set_cs", b"set_cs", "set_tr01_pwr", b"set_tr01_pwr", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["get_gpo", b"get_gpo", "send_spi_data", b"send_spi_data", "set_auto_cs_mode", b"set_auto_cs_mode", "set_cs", b"set_cs", "set_tr01_pwr", b"set_tr01_pwr", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_type: _TypeAlias = _typing.Literal["send_spi_data", "set_auto_cs_mode", "set_cs", "set_tr01_pwr", "get_gpo"]  # noqa: Y015
    _WhichOneofArgType_type: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_type) -> _WhichOneofReturnType_type | None: ...

Global___RawCmd: _TypeAlias = RawCmd  # noqa: Y015

@_typing.final
class SendSpiDataCmd(_message.Message):
    """------------------------------- SendSpiDataCmd"""

    DESCRIPTOR: _descriptor.Descriptor

    TX_DATA_FIELD_NUMBER: _builtins.int
    TIMEOUT_MS_FIELD_NUMBER: _builtins.int
    tx_data: _builtins.bytes
    timeout_ms: _builtins.int
    def __init__(
        self,
        *,
        tx_data: _builtins.bytes = ...,
        timeout_ms: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["timeout_ms", b"timeout_ms", "tx_data", b"tx_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SendSpiDataCmd: _TypeAlias = SendSpiDataCmd  # noqa: Y015

@_typing.final
class SetAutoCsModeCmd(_message.Message):
    """------------------------------- SetAutoCsModeCmd"""

    DESCRIPTOR: _descriptor.Descriptor

    ON_FIELD_NUMBER: _builtins.int
    on: _builtins.bool
    def __init__(
        self,
        *,
        on: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["on", b"on"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetAutoCsModeCmd: _TypeAlias = SetAutoCsModeCmd  # noqa: Y015

@_typing.final
class SetCsCmd(_message.Message):
    """------------------------------- SetCsCmd"""

    DESCRIPTOR: _descriptor.Descriptor

    HIGH_FIELD_NUMBER: _builtins.int
    high: _builtins.bool
    def __init__(
        self,
        *,
        high: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["high", b"high"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetCsCmd: _TypeAlias = SetCsCmd  # noqa: Y015

@_typing.final
class SetTr01PwrCmd(_message.Message):
    """------------------------------- SetTr01PwrCmd"""

    DESCRIPTOR: _descriptor.Descriptor

    ON_FIELD_NUMBER: _builtins.int
    on: _builtins.bool
    def __init__(
        self,
        *,
        on: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["on", b"on"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetTr01PwrCmd: _TypeAlias = SetTr01PwrCmd  # noqa: Y015

@_typing.final
class GetGpoCmd(_message.Message):
    """------------------------------- GetGpoCmd
    Empty command used to read TROPIC01 GPO pin.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetGpoCmd: _TypeAlias = GetGpoCmd  # noqa: Y015

@_typing.final
class RawResp(_message.Message):
    """================================= RawResp ================================="""

    DESCRIPTOR: _descriptor.Descriptor

    SEND_SPI_DATA_FIELD_NUMBER: _builtins.int
    SET_AUTO_CS_MODE_FIELD_NUMBER: _builtins.int
    SET_CS_FIELD_NUMBER: _builtins.int
    SET_TR01_PWR_FIELD_NUMBER: _builtins.int
    GET_GPO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def send_spi_data(self) -> Global___SendSpiDataResp: ...
    @_builtins.property
    def set_auto_cs_mode(self) -> Global___SetAutoCsModeResp: ...
    @_builtins.property
    def set_cs(self) -> Global___SetCsResp: ...
    @_builtins.property
    def set_tr01_pwr(self) -> Global___SetTr01PwrResp: ...
    @_builtins.property
    def get_gpo(self) -> Global___GetGpoResp: ...
    def __init__(
        self,
        *,
        send_spi_data: Global___SendSpiDataResp | None = ...,
        set_auto_cs_mode: Global___SetAutoCsModeResp | None = ...,
        set_cs: Global___SetCsResp | None = ...,
        set_tr01_pwr: Global___SetTr01PwrResp | None = ...,
        get_gpo: Global___GetGpoResp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["get_gpo", b"get_gpo", "send_spi_data", b"send_spi_data", "set_auto_cs_mode", b"set_auto_cs_mode", "set_cs", b"set_cs", "set_tr01_pwr", b"set_tr01_pwr", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["get_gpo", b"get_gpo", "send_spi_data", b"send_spi_data", "set_auto_cs_mode", b"set_auto_cs_mode", "set_cs", b"set_cs", "set_tr01_pwr", b"set_tr01_pwr", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_type: _TypeAlias = _typing.Literal["send_spi_data", "set_auto_cs_mode", "set_cs", "set_tr01_pwr", "get_gpo"]  # noqa: Y015
    _WhichOneofArgType_type: _TypeAlias = _typing.Literal["type", b"type"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_type) -> _WhichOneofReturnType_type | None: ...

Global___RawResp: _TypeAlias = RawResp  # noqa: Y015

@_typing.final
class SendSpiDataResp(_message.Message):
    """------------------------------- SendSpiDataResp"""

    DESCRIPTOR: _descriptor.Descriptor

    RES_CODE_FIELD_NUMBER: _builtins.int
    RX_DATA_FIELD_NUMBER: _builtins.int
    res_code: Global___SendSpiDataRespCode.ValueType
    rx_data: _builtins.bytes
    def __init__(
        self,
        *,
        res_code: Global___SendSpiDataRespCode.ValueType = ...,
        rx_data: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["res_code", b"res_code", "rx_data", b"rx_data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SendSpiDataResp: _TypeAlias = SendSpiDataResp  # noqa: Y015

@_typing.final
class SetAutoCsModeResp(_message.Message):
    """------------------------------- SetAutoCsModeResp"""

    DESCRIPTOR: _descriptor.Descriptor

    RES_CODE_FIELD_NUMBER: _builtins.int
    res_code: Global___SetAutoCsModeRespCode.ValueType
    def __init__(
        self,
        *,
        res_code: Global___SetAutoCsModeRespCode.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["res_code", b"res_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetAutoCsModeResp: _TypeAlias = SetAutoCsModeResp  # noqa: Y015

@_typing.final
class SetCsResp(_message.Message):
    """------------------------------- SetCsResp"""

    DESCRIPTOR: _descriptor.Descriptor

    RES_CODE_FIELD_NUMBER: _builtins.int
    res_code: Global___SetCsRespCode.ValueType
    def __init__(
        self,
        *,
        res_code: Global___SetCsRespCode.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["res_code", b"res_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetCsResp: _TypeAlias = SetCsResp  # noqa: Y015

@_typing.final
class SetTr01PwrResp(_message.Message):
    """------------------------------- SetTr01PwrResp"""

    DESCRIPTOR: _descriptor.Descriptor

    RES_CODE_FIELD_NUMBER: _builtins.int
    res_code: Global___SetTr01PwrRespCode.ValueType
    def __init__(
        self,
        *,
        res_code: Global___SetTr01PwrRespCode.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["res_code", b"res_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SetTr01PwrResp: _TypeAlias = SetTr01PwrResp  # noqa: Y015

@_typing.final
class GetGpoResp(_message.Message):
    """------------------------------- GetGpoResp"""

    DESCRIPTOR: _descriptor.Descriptor

    RES_CODE_FIELD_NUMBER: _builtins.int
    HIGH_FIELD_NUMBER: _builtins.int
    res_code: Global___GetGpoRespCode.ValueType
    high: _builtins.bool
    def __init__(
        self,
        *,
        res_code: Global___GetGpoRespCode.ValueType = ...,
        high: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["high", b"high", "res_code", b"res_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___GetGpoResp: _TypeAlias = GetGpoResp  # noqa: Y015

@_typing.final
class ErrorResp(_message.Message):
    """================================ ErrorResp ================================"""

    DESCRIPTOR: _descriptor.Descriptor

    RES_CODE_FIELD_NUMBER: _builtins.int
    res_code: Global___ErrorRespCode.ValueType
    def __init__(
        self,
        *,
        res_code: Global___ErrorRespCode.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["res_code", b"res_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ErrorResp: _TypeAlias = ErrorResp  # noqa: Y015
