name: Build docs and release (master)
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Install Doxygen and Graphviz
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: doxygen graphviz
          version: 1.0  # Version of cache to load. Each version will have its own cache.

      - name: Build docs
        uses: threeal/cmake-action@v2.0.0
        with:
          source-dir: ./
          build-dir: build
          options: |
            BUILD_DOCS=ON
            USE_TREZOR_CRYPTO=ON

      - name: Archive HTML docs
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'libtropic-html-docs.zip'
          directory: 'build/docs/doxygen/html/'

      - name: Upload HTML docs release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: 'build/docs/doxygen/html/libtropic-html-docs.zip'
          makeLatest: true
          name: 'HTML Documentation'
          prerelease: false
          replacesArtifacts: true
          tag: 'latest'
