name: Build docs and release to GitHub Pages from master
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: tropicsquare/github-actions/checkout-4.2.2@main

      - name: Install Doxygen and Graphviz
        uses: tropicsquare/github-actions/cache-apt-pkgs-action-1.4.3@main
        with:
          packages: doxygen graphviz
          version: 1.0  # Version of cache to load. Each version will have its own cache.

      - name: Build docs
        uses: tropicsquare/github-actions/cmake-action-2.1.0@main
        with:
          source-dir: ./
          build-dir: build
          options: |
            LT_BUILD_DOCS=ON
            LT_USE_TREZOR_CRYPTO=ON

      - name: Upload built html as artifact
        id: html_artifact
        uses: tropicsquare/github-actions/upload-pages-artifact-3.0.1@main
        with:
          path: build/docs/doxygen/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.html_artifact.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: pages_deployment
        uses: tropicsquare/github-actions/deploy-pages-4.0.5@main
